added git repo 2

diff --git a/charts/rstudio/source/Dockerfile b/charts/rstudio/source/Dockerfile
--- a/charts/rstudio/source/Dockerfile
+++ b/charts/rstudio/source/Dockerfile
@@ -7,6 +7,21 @@ ENV PATH=/usr/lib/rstudio-server/bin:$PATH
 
 RUN /rocker_scripts/install_rstudio.sh
 RUN /rocker_scripts/install_shiny_server.sh
+# Install libglpk40 alone and check if it's installed
+
+# Install libglpk40 alone and check if it's installed
+RUN echo "------------------------------" && \
+    echo "Installing libglpk40..." && \
+    apt-get update && apt-get install --no-install-recommends -y libglpk40 && \
+    apt-get clean && rm -rf /var/lib/apt/lists/* && \
+    echo "------------------------------"
+
+# Check if libglpk40 is installed and visible
+RUN echo "------------------------------" && \
+    echo "Checking if libglpk40 is installed..." && \
+    ldconfig -p | grep libglpk && \
+    dpkg -s libglpk40 || echo "libglpk40 not found" && \
+    echo "------------------------------"
 
 RUN apt-get update && apt-get upgrade -y && apt-get install --no-install-recommends -y \
     apt-utils \
@@ -25,12 +40,6 @@ RUN apt-get update && apt-get upgrade -y && apt-get install --no-install-recomme
     nano && \
     apt-get clean && rm -rf /var/lib/apt/lists/*
 
-# Check if libglpk40 is installed and visible
-RUN echo "------------------------------" && \
-    echo "Checking if libglpk40 is installed..." && \
-    ldconfig -p | grep libglpk && \
-    dpkg -s libglpk40 || echo "libglpk40 not found" && \
-    echo "------------------------------"
 # Setup various variables
 ENV TZ="Europe/Helsinki" \
     USERNAME="rstudio-server" \
